web/models/Turn.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use app\components\Model;
use yii\helpers\ArrayHelper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "turn".
 *
 * @property int $id
 * @property int|null $admin_id
 * @property string $visitDate
 * @property int|null $visitType
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 * @property int|null $deleted_at
 */
class Turn extends \yii\db\ActiveRecord
{
    const STATUS_REJECT = 1;
    const STATUS_PENDING = 9;
    const STATUS_APPROVE = 10;
    const STATUS_VISITED = 11;

    const TYPE_ONLINE = 1;
    const TYPE_PRESENCE = 2;

    public $visitDateTimeStamp;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'turn';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['visitDate', 'status', 'visitType'], 'required'],
            [['admin_id', 'visitType', 'status', 'created_at', 'updated_at','visitDateTimeStamp'], 'integer'],
            [['visitDate'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'شماره نوبت',
            'admin_id' => 'ادمین ایجاد کننده',
            'visitDate' => 'تاریخ ویزیت',
            'visitType' => 'نوع ویزیت',
            'status' => 'وضعیت',
            'created_at' => 'تاریخ ایجاد',
            'updated_at' => 'آپدیت شده در',
            'deleted_at' => 'Deleted At',
        ];
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            [
                'class' => BlameableBehavior::className(),
                'value' => Yii::$app->admin->id,
                'createdByAttribute' => 'admin_id',
                'updatedByAttribute' => null,
            ]
        ];
    }

    public static function statusList()
    {
        return [
            self::STATUS_REJECT => 'رد شده',
            self::STATUS_PENDING => 'در حال برسی',
            self::STATUS_APPROVE => 'تایید شده',
            self::STATUS_VISITED => 'ویزیت شده',
        ];
    }

    public function getStatusText()
    {
        if(isset(self::statusList()[$this->status])){
            return self::statusList()[$this->status];
        }
        return '-';
    }

    public static function typeList()
    {
        return [
            self::TYPE_ONLINE => 'آنلاین',
            self::TYPE_PRESENCE => 'حضوری',
        ];
    }

    public function beforeSave($insert)
    {
        $this->visitDate = $this->visitDateTimeStamp / 1000;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getTypeText()
    {
        if(isset(self::typeList()[$this->visitType])){
            return self::typeList()[$this->visitType];
        }
        return '-';
    }

    public function getTurnPeople()
    {
        return $this->hasMany(TurnPeople::className(), ['turn_id' => 'id']);
    }

    public function SaveData($TurnPeoples)
    {
        $transaction = \Yii::$app->db->beginTransaction();
        try {
            if ($flag = $this->save(false)) {

                TurnPeople::DeleteAll(['turn_id'=>$this->id]);

                foreach ($TurnPeoples as $EachTurnPeoples) {
                    $EachTurnPeoples->turn_id = $this->id;
                    if (!($flag = $EachTurnPeoples->save(false))) {
                        $transaction->rollBack();
                        return false;
                    }

                }
            }
            if ($flag) {
                $transaction->commit();
                return $this->id;
            }
        } catch (\Exception $e) {
            $transaction->rollBack();
            return false;
        }
    }
}

web/controllers/PatientController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Turn;
use app\models\Patient;
use app\models\PatientSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\data\ActiveDataProvider;

/**
 * PatientController implements the CRUD actions for Patient model.
 */
class PatientController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [ 'class' => AccessControl::className(),
                'user' => Yii::$app->admin,
                'only' => ['index','create','view','delete','update','get-patient-list'],
                'rules' => [
                    [
                        'actions' => ['index','create','view','delete','update','get-patient-list'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Patient models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PatientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Patient model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        $turnDataProvider = new ActiveDataProvider([
            'query' => Turn::find()->where(['id'=>array_column($model->turnPeople,'turn_id'),'deleted_at'=>null])
        ]);

        return $this->render('view', [
            'model' => $model,
            'turnDataProvider' => $turnDataProvider
        ]);
    }

    /**
     * Creates a new Patient model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */

    public function actionCreate()
    {
        $model = new Patient();



        if ($model->load(Yii::$app->request->post())) {

            // ajax process
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                if ($model->save()) {
                    return [
                        'data' => [
                            'success' => true,
                            'model' => $model,
                        ],
                    ];
                }
                return [
                    'data' => [
                        'success' => false,
                        'errors' => $model->errors,
                    ],
                ];
            }
            // end ajax

            if($model->save()){
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }


    /**
     * ajax search to find Patient
     * @param string $q
     */
    public function actionGetPatientList($q){
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $Patients = Patient::find()
            ->OrWhere("`mobile` LIKE '%{$q}%'")
            ->OrWhere("`first_name` LIKE '%{$q}%'")
            ->OrWhere("`last_name` LIKE '%{$q}%'")
            ->andWhere(['deleted_at'=>null])
            ->all();
        $out = [];
        foreach ($Patients as $k => $data) {
            $out['results'][$k]['id'] = $data['id'];
            $out['results'][$k]['text'] = $data['first_name'] . ' ' . $data['last_name'] . ' ( '.  $data['mobile'].' )';
        }
        return $out;
    }
    /**
     * Updates an existing Patient model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Patient model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->deleted_at = time();
        $model->save(false);
        Yii::$app->redis->DECR('patientCount');

        return $this->redirect(['index?sort=-id']);
    }

    /**
     * Finds the Patient model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return pPatient the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Patient::findOne(['id'=>$id,'deleted_at'=>null])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

web/controllers/TurnController.php
<?php

namespace app\controllers;


use app\components\Model;
use Yii;
use app\models\Turn;
use app\models\TurnSearch;
use app\models\TurnPeople;
use app\models\Patient;
use yii\base\BaseObject;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\UploadedFile;

/**
 * TurnController implements the CRUD actions for Turn model.
 */
class TurnController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
        {
            return [
                    'access' => [ 'class' => AccessControl::className(),
                    'user' => Yii::$app->admin,
                    'only' => ['index','create','view','delete','update'],
                    'rules' => [
                    [
                        'actions' => ['index','create','view','delete','update'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Turn models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TurnSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Turn model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $turnPeoples = $model->turnPeople;
        return $this->render('view', [
            'model' => $model,
            'turnPeoples' => $turnPeoples,
        ]);
    }

    /**
     * Creates a new Turn model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new Turn();
        $TurnPeoples = [new TurnPeople()];
        $model->status = Turn::STATUS_PENDING;


        if ($model->load(Yii::$app->request->post())) {

            $TurnPeoples = Model::createMultiple(TurnPeople::classname());
            Model::loadMultiple($TurnPeoples, Yii::$app->request->post());
            $isValidDynamicForm = Model::validateMultiple($TurnPeoples);


            if ($isValidDynamicForm && $model->validate() && $model->SaveData($TurnPeoples)) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }


        return $this->render('create', [
            'model' => $model,
            'patientModel' => new Patient(),
            'TurnPeoples' => (empty($TurnPeoples)) ? [new TurnPeople] : $TurnPeoples
        ]);
    }

    /**
     * Updates an existing Turn model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);


        // load turnPeople For Dynamic Form
        $TurnPeoples = $model->turnPeople;


        if ($model->load(Yii::$app->request->post())) {


            $TurnPeoples = Model::createMultiple(TurnPeople::classname(), $TurnPeoples);
            Model::loadMultiple($TurnPeoples, Yii::$app->request->post());
            $isValidDynamicForm = Model::validateMultiple($TurnPeoples);

            if ($isValidDynamicForm && $model->validate() && $model->SaveData($TurnPeoples)) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'patientModel' => new Patient(),
            'TurnPeoples' => (empty($TurnPeoples)) ? [new TurnPeople()] : $TurnPeoples
        ]);
    }

    /**
     * Deletes an existing Turn model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->deleted_at = time();
        $model->save(false);
        return $this->redirect(['index?sort=-id']);
    }

    /**
     * Finds the Turn model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Turn the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Turn::findOne(['id' => $id, 'deleted_at' => null])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

web/views/turn/_form.php
<?php

use app\models\Turn;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use wbraganca\dynamicform\DynamicFormWidget;
use kartik\select2\Select2;
use yii\web\JsExpression;

/* @var $this yii\web\View */
/* @var $model app\models\Turn */
/* @var $form yii\widgets\ActiveForm */

?>

<?php

$js = '
jQuery(".dynamicform_wrapper").on("afterInsert", function(e, item) {
    console.log("pk");
    jQuery(".dynamicform_wrapper .panel-title-address").each(function(index) {
        jQuery(this).html("بیمار: " + (index + 1))
    });
});

jQuery(".dynamicform_wrapper").on("afterDelete", function(e) {
    jQuery(".dynamicform_wrapper .panel-title-address").each(function(index) {
        jQuery(this).html("بیمار: " + (index + 1))
    });
});


$("#patientForms").submit(function(event) {

    event.preventDefault(); // stopping submitting
    event.stopImmediatePropagation(); // stopping submitting

    var url = $(this).attr("action");
    $.ajax({
        url: url,
        type: "post",
        contentType: false,
        processData: false,
        data: new FormData(this),
    })
    .done(function(response) {
        if (response.data.success == true) {
        
            // hide Modal 
            $("#patientModal").modal("toggle");
            
            // remove fade 
            $("body").removeClass("modal-open");
            $(".modal-backdrop").remove();

            // show alert
            Swal.fire({
              icon: "success",
              title: "تبریک",
              text: "اطلاعات بیمار با موفقیت ثبت شد. نام بیمار: " + response.data.model.first_name,
              confirmButtonText: "بستن"
            })
        }
        else if (response.data.success == false) {
            Swal.fire({
              icon: "error",
              title: "خطا",
              text: Object.values(response.data.errors),
              confirmButtonText: "بستن"
            })
        }
    })
    .fail(function() {
        console.log("error");
    });

});
    

$("#visitDate").pDatepicker({
    format: "DD , MMMM , YYYY",
    autoClose: true,
    altField: "#visitDateTimeStamp",
    initialValueType: "persian",
    minDate: new persianDate().unix()
});

';

$this->registerJs($js);
?>


<!-- Modal -->
<div class="modal fade" id="patientModal"  data-toggle="modal" stabindex="-1" role="dialog" data-dismiss="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <?= $this->render('/patient/_form', [
                    'model' => $patientModel,
                    'action' => ['patient/create']
                ]) ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
            </div>

        </div>
    </div>
</div>

<div class="turn-form">

    <div class="row">
        <div class="col-md-6" style="margin-bottom: 20px;direction: ltr">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#patientModal">
                تعریف بیمار جدید
            </button>
        </div>
    </div>

    <?php $form = ActiveForm::begin(['id' => 'dynamic-form']); ?>
    <div class="row">

        <div class="col-md-4">
            <div class="card card-body">
                <?= $form->field($model, 'visitDate')->textInput(['maxlength' => true,'id'=>'visitDate','value'=>($model->isNewRecord ? '' : \app\components\Jdf::jdate("Y-m-d",$model->visitDate))]) ?>
                <?= $form->field($model, 'visitDateTimeStamp')->hiddenInput(['id'=>'visitDateTimeStamp'])->label(false) ?>

                <?= $form->field($model, 'visitType')->dropDownList(Turn::typeList()) ?>

                <?= $form->field($model, 'status')->dropDownList(Turn::statusList()) ?>
            </div>
        </div>

        <div class="col-md-8">
            <div class="card card-body">
                <?php DynamicFormWidget::begin([
                    'widgetContainer' => 'dynamicform_wrapper', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
                    'widgetBody' => '.container-items', // required: css class selector
                    'widgetItem' => '.item', // required: css class
//            'limit' => 4, // the maximum times, an element can be cloned (default 999)
                    'min' => 1, // 0 or 1 (default 1)
                    'insertButton' => '.add-item', // css class
                    'deleteButton' => '.remove-item', // css class
                    'model' => $TurnPeoples[0],
                    'formId' => 'dynamic-form',
                    'formFields' => [
                        'patient_id'
                    ],
                ]); ?>
                <div class="panel panel-default">
                    <div class="panel-body container-items"><!-- widgetContainer -->
                        <?php foreach ($TurnPeoples as $index => $EachModel): ?>
                            <div class="item panel panel-default"><!-- widgetBody -->
                                <div>
                                    <div class="row">
                                        <div class="col-md-3" style="margin-bottom: 20px">
                                            <span class="panel-title-address">بیمار: <?= ($index + 1) ?></span> &nbsp;
                                            <button type="button" class="pull-right remove-item btn btn-danger btn-xs">
                                                حذف
                                            </button> &nbsp;
                                            <div class="clearfix"></div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-sm-8">
                                            <?= $form->field($EachModel, "[{$index}]patient_id")->widget(Select2::classname(), [
                                                'data' => \app\models\Patient::getAllUser(),
                                                'initValueText' => '1',
                                                'options' => [
                                                    'placeholder' => 'نام/ شماره بیمار',
                                                    'dir' => 'rtl',
                                                ],
                                                'pluginOptions' => [
                                                    'allowClear' => true,
                                                    'minimumInputLength' => 2,
                                                    'ajax' => [
                                                        'url' => Url::to(['/patient/get-patient-list']),
                                                        'dataType' => 'json',
                                                        'data' => new JsExpression('function(params) { return {q:params.term}; }'),
                                                    ],
                                                ],
                                            ])->label('نام یا شماره تلفن بیمار را وارید نمایید'); ?>
                                        </div>
                                    </div><!-- end:row -->

                                </div>
                                <hr/>
                            </div>
                        <?php endforeach; ?>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <button type="button" class="pull-right add-item btn btn-success btn-xs"><i
                                        class="fa fa-plus"></i> بیمار جدید برای این نوبت
                            </button>
                            <div class="clearfix"></div>
                        </div>
                    </div>

                </div>
                <?php DynamicFormWidget::end(); ?>
            </div>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton('ثبت', ['class' => 'btn btn-success']) ?>
    </div>
    <?php ActiveForm::end(); ?>

</div>

web/views/turn/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Turn;
use app\components\Jdf;

/* @var $this yii\web\View */
/* @var $model app\models\TurnSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="turn-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <div class="row">

        <div class="col-md-3">
            <label class="control-label">از تاریخ</label>
            <input type="text" class="form-control fromTime" placeholder="از تاریخ"  <?= (isset($_GET['TurnSearch']['fromTime']) ? 'value="'. Jdf::jdate("Y-m-d", $_GET['TurnSearch']['fromTime'] / 1000) .'"' : '') ?> />
        </div>
        <div class="col-md-3">
            <label class="control-label">تا تاریخ</label>
            <input type="text" class="form-control toTime" placeholder="تا تاریخ" <?= (isset($_GET['TurnSearch']['toTime']) ? 'value="' .  Jdf::jdate("Y-m-d", $_GET['TurnSearch']['toTime'] / 1000) . '"' : '') ?> />
        </div>

    </div>

    <?= Html::hiddenInput('TurnSearch[fromTime]','',['id'=>'fromTime']); ?>
    <?= Html::hiddenInput('TurnSearch[toTime]','',['id'=>'toTime']); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'visitType')->dropDownList(Turn::typeList(),['prompt' => 'لطفا انتخاب کنید']) ?>

    <?= $form->field($model, 'status')->dropDownList(Turn::statusList(),['prompt' => 'لطفا انتخاب کنید']) ?>

    <div class="form-group">
        <?= Html::submitButton('جست وجو', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

web/views/turn/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Turn */

$this->title = 'ایجاد نوبت جدید';
$this->params['breadcrumbs'][] = ['label' => 'نوبت ها', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<?= $this->render('_form', [
    'model' => $model,
    'patientModel' => $patientModel,
    'TurnPeoples' => $TurnPeoples
]) ?>

web/views/turn/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\Turn;

/* @var $this yii\web\View */
/* @var $searchModel app\models\TurnSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'نوبت ها';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="card card-body">
    <?php  echo $this->render('_search', ['model' => $searchModel]); ?>

</div>
<div class="card card-body">




    <p>
        <?= Html::a('ایجاد نوبت جدید', ['create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            [
                'attribute' => 'visitDate',
                'value' => function($model){
                    return \app\components\Jdf::jdate("Y/m/d",$model->visitDate);
                }
            ],
            [
                'attribute' => 'visitType',
                'filter' => Turn::typeList(),
                'value' => function($model){
                    return $model->TypeText;
                }
            ],
            [
                'attribute' => 'status',
                'filter' => Turn::statusList(),
                'value' => function($model){
                    return $model->StatusText;
                }
            ],
            [
                'format' => 'raw',
                'label' => '*',
                'value' => function($model){
                    $html  = Html::a(Html::encode('ویرایش'), ['update', 'id' => $model->id],['class' => 'btn btn-success']) . ' ';
                    $html .= Html::a(Html::encode('جزیات'), ['view', 'id' => $model->id],['class' => 'btn btn-info']) . ' ';
                    $html .= Html::a('حذف', ['delete', 'id' => $model->id], [
                        'class' => 'btn btn-danger',
                        'data' => [
                        'confirm' => 'آیا از حذف این آیتم مطمئن هستید؟',
                        ],
                    ]) . ' ';
                    return $html;
                }
            ],
          //  ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

<?php

$js = '
$(".fromTime").pDatepicker({
    format: "DD , MMMM , YYYY",
    autoClose: true,
    altField: "#fromTime",
    initialValueType: "persian"
});
$(".toTime").pDatepicker({
    format: "DD , MMMM , YYYY",
    autoClose: true,
    altField: "#toTime",
    initialValueType: "persian"
});
';

$this->registerJs($js);

web/views/turn/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Turn */

$this->title = 'ویراش نوبت شماره: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'نوبت دهی', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' =>'نوبت شماره '. $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'ویرایش';
?>

<?= $this->render('_form', [
    'model' => $model,
    'TurnPeoples' => $TurnPeoples,
    'patientModel' => $patientModel,
]) ?>

web/views/turn/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\grid\GridView;
use app\components\Jdf;
/* @var $this yii\web\View */
/* @var $model app\models\Turn */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'نوبت دهی', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);

?>
<div class="card card-body">

    <p>
        <?= Html::a('ویرایش نوبت', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('حذف نوبت', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'آیا از حذف این آیتم مطمئن هستید؟',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
//            'admin_id',
            [
                'attribute' => 'visitDate',
                'value' => function($model){
                    return Jdf::jdate("Y/m/d",$model->visitDate);
                }
            ],
            [
                'attribute' => 'visitType',
                'value' => $model->TypeText
            ],
            [
                'attribute' => 'status',
                'value' => $model->StatusText
            ],
            [
                'attribute' => 'created_at',
                'value' => function($model){
                    return Jdf::jdate("Y/m/d",$model->created_at);
                }
            ],
        ],
    ]) ?>

</div>

<div class="card card-body">
    <div class="alert alert-primary" role="alert">
        <div class="alert-body">لیست بیماران:</div>
    </div>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>شماره بیمار</th>
            <th>نام</th>
            <th>نام خانوادگی</th>
            <th>موبایل</th>
            <th>عکس</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($turnPeoples as $turnPeople): if(!$turnPeople->patient)continue; ?>
            <tr>
                <td><?= Html::a($turnPeople->patient->id,['patient/view','id'=>$turnPeople->patient->id]) ?></td>
                <td><?= $turnPeople->patient->first_name?></td>
                <td><?= $turnPeople->patient->last_name?></td>
                <td><?= $turnPeople->patient->mobile?></td>
                <?php if($turnPeople->patient->picture): ?>
                    <td><?= Html::a('مشاهده عکس',$turnPeople->patient->getUrl(),['target'=>'_blank'])?></td>
                <?php else: ?>
                    <td>بدون عکس</td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

</div>