web/models/Patient.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;
use yii\helpers\ArrayHelper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "patient".
 *
 * @property int $id
 * @property int|null $admin_id
 * @property int|null $mobile
 * @property string $first_name
 * @property string $last_name
 * @property string|null $picture
 * @property int $created_at
 * @property int $updated_at
 * @property int|null $deleted_at
 */
class Patient extends \yii\db\ActiveRecord
{

    public $imageFile;
    public $PreventRunAfterSave = false;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'patient';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['first_name', 'last_name','mobile'], 'required'],
            [['admin_id', 'mobile', 'created_at', 'updated_at', 'deleted_at'], 'integer'],
            [['first_name', 'last_name', 'picture'], 'string', 'max' => 255],
            [['imageFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg'],
            ['mobile','uniqueCustom']
        ];
    }


    //  check we have a duplicate mobile or Not
    public function uniqueCustom($attribute, $params){


        if($this->isNewRecord){
            $FindPatient = Patient::find()->where(['mobile'=>$this->mobile,'deleted_at'=>null])->one();
        }
        else{
            $FindPatient = Patient::find()->where(['mobile'=>$this->mobile,'deleted_at'=>null])->andWhere("id != $this->id")->one();
        }

        if($FindPatient){
            $this->addError($attribute, 'این شماره موبایل قبلا ثبت شده است');
        }
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'شماره بیمار',
            'admin_id' => 'Admin ID',
            'mobile' => 'موبایل',
            'first_name' => 'نام',
            'last_name' => 'نام خانوادگی',
            'picture' => 'عکس',
            'imageFile' => 'عکس',
            'created_at' => 'زمان ایجاد',
            'updated_at' => 'زمان ویرایش',
            'deleted_at' => 'زمان حذف',
        ];
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            [
                'class' => BlameableBehavior::className(),
                'value' => Yii::$app->admin->id,
                'createdByAttribute' => 'admin_id',
                'updatedByAttribute' => null,
            ]
        ];
    }


    public function afterSave($insert, $changedAttributes)
    {
        $this->imageFile = UploadedFile::getInstance($this, 'imageFile');
        if($this->imageFile && $this->PreventRunAfterSave == false){
            $this->PreventRunAfterSave = true;
            $this->upload();
        }
        if($insert){
            Yii::$app->redis->INCR('patientCount');
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function upload()
    {
        if ($this->imageFile) {
            $name = $this->id . '-' . $this->imageFile->baseName . rand(100000, 999999) . '.' . $this->imageFile->extension;
            $this->imageFile->saveAs(Yii::$app->basePath . '/web/UploadFile/patient/' . $name);
            $this->imageFile = null;
            $this->picture = $name;
            $this->save(false);
        }
    }
    public function getUrl()
    {
        return Yii::getAlias('@web/UploadFile/patient/' . $this->picture);
    }

    public function getTurnPeople()
    {
        return $this->hasMany(TurnPeople::className(), ['patient_id' => 'id']);
    }

    public static function getAllUser(){
        return ArrayHelper::map(Patient::findAll(['deleted_at'=>null]),'id','mobile');
    }
}

web/controllers/PatientController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Turn;
use app\models\Patient;
use app\models\PatientSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\data\ActiveDataProvider;

/**
 * PatientController implements the CRUD actions for Patient model.
 */
class PatientController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [ 'class' => AccessControl::className(),
                'user' => Yii::$app->admin,
                'only' => ['index','create','view','delete','update','get-patient-list'],
                'rules' => [
                    [
                        'actions' => ['index','create','view','delete','update','get-patient-list'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Patient models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PatientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Patient model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        $turnDataProvider = new ActiveDataProvider([
            'query' => Turn::find()->where(['id'=>array_column($model->turnPeople,'turn_id'),'deleted_at'=>null])
        ]);

        return $this->render('view', [
            'model' => $model,
            'turnDataProvider' => $turnDataProvider
        ]);
    }

    /**
     * Creates a new Patient model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */

    public function actionCreate()
    {
        $model = new Patient();



        if ($model->load(Yii::$app->request->post())) {

            // ajax process
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                if ($model->save()) {
                    return [
                        'data' => [
                            'success' => true,
                            'model' => $model,
                        ],
                    ];
                }
                return [
                    'data' => [
                        'success' => false,
                        'errors' => $model->errors,
                    ],
                ];
            }
            // end ajax

            if($model->save()){
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }


    /**
     * ajax search to find Patient
     * @param string $q
     */
    public function actionGetPatientList($q){
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $Patients = Patient::find()
            ->OrWhere("`mobile` LIKE '%{$q}%'")
            ->OrWhere("`first_name` LIKE '%{$q}%'")
            ->OrWhere("`last_name` LIKE '%{$q}%'")
            ->andWhere(['deleted_at'=>null])
            ->all();
        $out = [];
        foreach ($Patients as $k => $data) {
            $out['results'][$k]['id'] = $data['id'];
            $out['results'][$k]['text'] = $data['first_name'] . ' ' . $data['last_name'] . ' ( '.  $data['mobile'].' )';
        }
        return $out;
    }
    /**
     * Updates an existing Patient model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Patient model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->deleted_at = time();
        $model->save(false);
        Yii::$app->redis->DECR('patientCount');

        return $this->redirect(['index?sort=-id']);
    }

    /**
     * Finds the Patient model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return pPatient the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Patient::findOne(['id'=>$id,'deleted_at'=>null])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

web/controllers/TurnController.php
<?php

namespace app\controllers;


use app\components\Model;
use Yii;
use app\models\Turn;
use app\models\TurnSearch;
use app\models\TurnPeople;
use app\models\Patient;
use yii\base\BaseObject;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\UploadedFile;

/**
 * TurnController implements the CRUD actions for Turn model.
 */
class TurnController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
        {
            return [
                    'access' => [ 'class' => AccessControl::className(),
                    'user' => Yii::$app->admin,
                    'only' => ['index','create','view','delete','update'],
                    'rules' => [
                    [
                        'actions' => ['index','create','view','delete','update'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Turn models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TurnSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Turn model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $turnPeoples = $model->turnPeople;
        return $this->render('view', [
            'model' => $model,
            'turnPeoples' => $turnPeoples,
        ]);
    }

    /**
     * Creates a new Turn model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new Turn();
        $TurnPeoples = [new TurnPeople()];
        $model->status = Turn::STATUS_PENDING;


        if ($model->load(Yii::$app->request->post())) {

            $TurnPeoples = Model::createMultiple(TurnPeople::classname());
            Model::loadMultiple($TurnPeoples, Yii::$app->request->post());
            $isValidDynamicForm = Model::validateMultiple($TurnPeoples);


            if ($isValidDynamicForm && $model->validate() && $model->SaveData($TurnPeoples)) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }


        return $this->render('create', [
            'model' => $model,
            'patientModel' => new Patient(),
            'TurnPeoples' => (empty($TurnPeoples)) ? [new TurnPeople] : $TurnPeoples
        ]);
    }

    /**
     * Updates an existing Turn model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);


        // load turnPeople For Dynamic Form
        $TurnPeoples = $model->turnPeople;


        if ($model->load(Yii::$app->request->post())) {


            $TurnPeoples = Model::createMultiple(TurnPeople::classname(), $TurnPeoples);
            Model::loadMultiple($TurnPeoples, Yii::$app->request->post());
            $isValidDynamicForm = Model::validateMultiple($TurnPeoples);

            if ($isValidDynamicForm && $model->validate() && $model->SaveData($TurnPeoples)) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'patientModel' => new Patient(),
            'TurnPeoples' => (empty($TurnPeoples)) ? [new TurnPeople()] : $TurnPeoples
        ]);
    }

    /**
     * Deletes an existing Turn model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->deleted_at = time();
        $model->save(false);
        return $this->redirect(['index?sort=-id']);
    }

    /**
     * Finds the Turn model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Turn the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Turn::findOne(['id' => $id, 'deleted_at' => null])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

web/views/patient/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\patient */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="card card-body">

    <?php $form = ActiveForm::begin([
            'id'=>'patientForms',
            'action' => $action, // get action url, in
            'options' => ['enctype' => 'multipart/form-data']
    ]); ?>

    <?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'mobile')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'imageFile')->fileInput() ?>


    <div class="form-group">
        <?= Html::submitButton('ثبت', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

web/views/patient/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\patientSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="patient-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'first_name') ?>

    <?= $form->field($model, 'last_name') ?>

    <?= $form->field($model, 'picture') ?>

    <?= $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'deleted_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

web/views/patient/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\patient */

$this->title = 'بیمار جدید';
$this->params['breadcrumbs'][] = ['label' => 'بیماران', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="patient-create">

    <?= $this->render('_form', [
        'model' => $model,
        'action' => ''
    ]) ?>

</div>

web/views/patient/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PatientSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'بیماران';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="card card-body">

    <p>
        <?= Html::a('بیمار جدید', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
//            'id',
            'first_name',
            'last_name',
            'mobile',
            [
                'attribute' => 'created_at',
                'value' => function($model){
                    return \app\components\Jdf::jdate("Y/m/d H:i",$model->created_at);
                }
            ],

            [
                'format' => 'raw',
                'label' => '*',
                'value' => function($model){
                    $html  = Html::a(Html::encode('ویرایش'), ['update', 'id' => $model->id],['class' => 'btn btn-success']) . ' ';
                    $html .= Html::a(Html::encode('جزیات'), ['view', 'id' => $model->id],['class' => 'btn btn-info']) . ' ';
                    $html .= Html::a('حذف', ['delete', 'id' => $model->id], [
                            'class' => 'btn btn-danger',
                            'data' => [
                                'confirm' => 'آیا از حذف این آیتم مطمئن هستید؟',
                            ],
                        ]) . ' ';
                    return $html;
                }
            ],
//            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

web/views/patient/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\patient */

$this->title = 'ویرایش بیمار: ' . $model->first_name;
$this->params['breadcrumbs'][] = ['label' => 'بیماران', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->first_name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'ویرایش';
?>
<div class="patient-update">

    <?= $this->render('_form', [
        'model' => $model,
        'action' => '',
    ]) ?>

</div>

web/views/patient/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\components\Jdf;
use yii\grid\GridView;
use app\models\Turn;

/* @var $this yii\web\View */
/* @var $model app\models\patient */
$this->title = $model->first_name;
$this->params['breadcrumbs'][] = ['label' => 'بیماران', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="card card-body">

    <p>
        <?= Html::a('ویرایش', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('حذف', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'آیا از حذف این بیمار مطمعن هستید؟',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'first_name',
            'last_name',
            [
                'format' => 'raw',
                'attribute' => 'created_at',
                'value' => function ($model) {
                    if ($model->picture) {
                        return Html::a('مشاهده عکس', $model->getUrl(), ['target' => '_blank']);
                    }
                    return 'بدون عکس';
                }
            ],
            [
                'attribute' => 'created_at',
                'value' => function ($model) {
                    return Jdf::jdate("Y/m/d H:i", $model->created_at);
                }
            ],
            [
                'attribute' => 'updated_at',
                'value' => function ($model) {
                    return Jdf::jdate("Y/m/d H:i", $model->updated_at);
                }
            ]
//            'deleted_at',
        ],
    ]) ?>

</div>

<div class="card card-body">
    <div class="alert alert-primary" role="alert">
        <div class="alert-body">لیست نوبت های این بیمار:</div>
    </div>

    <?= GridView::widget([
        'dataProvider' => $turnDataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            [
                'attribute' => 'visitDate',
                'value' => function($model){
                    return Jdf::jdate("Y/m/d",$model->visitDate);
                }
            ],
            [
                'attribute' => 'visitType',
                'filter' => Turn::typeList(),
                'value' => function ($model) {
                    return $model->TypeText;
                }
            ],
            [
                'attribute' => 'status',
                'filter' => Turn::statusList(),
                'value' => function ($model) {
                    return $model->StatusText;
                }
            ],
            [
                'format' => 'raw',
                'label' => '*',
                'value' => function ($model) {
                    return Html::a(Html::encode('جزیات'), ['turn/view', 'id' => $model->id], ['class' => 'btn btn-info']) . ' ';
                }
            ],
            //  ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>